---
title: "TAMAULIPAS ANÁLISIS POR DOMINIOS"
author: "Oscar Garcia Hernandez"
date: "20/8/2019"
output: html_document
---

```{r setup, include=FALSE, }
knitr::opts_chunk$set(echo = FALSE,
                      fig.width=10, 
                      fig.height=10, 
                      message=FALSE, 
                      results='hide',
                      fig.align = 'center')
library(knitr)
```

# INTRODUCCION

En este informe se pretende comprobar el funcionamiento del modelo para el parque de Tamaulipas en 1 mes. Teniendo 3 Dominios en los que se aumenta la correlacion. 

```{r fig.width=10, fig.height=10, echo=FALSE, message=FALSE, results='hide'}
library(here)
source(here::here('libraries.R'))
library(tools)
library(maps)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(OpenStreetMap)

LISTA_DATOS_LEVELS<- readRDS(here::here('Data/Parques/PRUEBA_EOLICOS/TAMAULIPAS_DATA/LISTA_DATOS.RDS'))
LISTA_CORR_LEVEL <- readRDS(here::here('Data/Parques/PRUEBA_EOLICOS/TAMAULIPAS_DATA/LISTA_CORRELATION.RDS'))

DATA_SIM_D01<- LISTA_DATOS_LEVELS$L1$D01
DATA_SIM_D02<-LISTA_DATOS_LEVELS$L1$D02
DATA_SIM_D03<-LISTA_DATOS_LEVELS$L1$D03

COORD_SIM_D01<- DATA_SIM_D01[,c("LON", 'LAT')] %>% unique()
COORD_SIM_D02<- DATA_SIM_D02[,c("LON", 'LAT')] %>% unique()
COORD_SIM_D03<- DATA_SIM_D03[,c("LON", 'LAT')] %>% unique()


LON_PARQUE<- -98.196080
LAT_PARQUE<- 25.78788

```

```{r}
TAMAULIPAS_MAP<- readRDS('/home/oscar/MB//Mapas/32.162_-91.78//bing15.RDS')
autoplot(TAMAULIPAS_MAP)+ 
  geom_point(aes(x= LON_PARQUE, y= LAT_PARQUE), cex= 3, col = 'red')
  

```


```{r fig.width=10, fig.height=10, echo=FALSE, message=FALSE, results='hide'}
library(rasterVis)
library(elevatr)



n=max(COORD_SIM_D01$LAT) 
s=min(COORD_SIM_D01$LAT)    
e=max(COORD_SIM_D01$LON)    
w=min(COORD_SIM_D01$LON) 

incr<- 0.0005


if(n > 0){n<- n + incr}else{n<- n + incr}
if(s > 0){s<- s - incr}else{s<- s- incr}
if(e > 0){e<- e + incr}else{e<- e + incr}
if(w > 0){w<- w - incr}else{w<- w- incr}



ul <- round(c(n,w),digits = 2)  #Upper Left
lr <- round(c(s,e), digits = 2)  #Lower Right


lon_location<- seq(lr[1],ul[1],length.out = 100 ) 
lat_location<- seq(ul[2],lr[2], length.out = 100)
data_loc<- expand.grid(lat_location,lon_location)
colnames(data_loc)<- c("x", "y")

spdf <- SpatialPointsDataFrame(coords = data_loc, data = data_loc,
                               proj4string = CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))

if(!dir.exists(here::here('Mapas/Raster_TAMAULIPAS/'))){dir.create(here::here('Mapas/Raster_TAMAULIPAS/'), recursive = T)}

if(file.exists(here::here('Mapas/Raster_TAMAULIPAS/map_raster1.RDS'))){
  map_raster1<- readRDS(here::here('Mapas/Raster_TAMAULIPAS/map_raster1.RDS'))
}else{
  map_raster1<- get_elev_raster(spdf, z=12)
  saveRDS(map_raster1,here::here('Mapas/Raster_TAMAULIPAS/map_raster1.RDS'))
}

levelplot(map_raster1, par.settings= viridisTheme()) + 
  layer(panel.points(COORD_SIM_D01$LON ,
                     COORD_SIM_D01$LAT, pch=21, cex=1, colour='white', fill= 'white'))+
  layer(panel.points(LON_PARQUE ,
                     LAT_PARQUE, pch=21, cex=1, colour='white', fill= 'red'))


```

```{r fig.width=10, fig.height=10, echo=FALSE, message=FALSE, results='hide'}
n=max(LAT_PARQUE) 
s=min(LAT_PARQUE)    
e=max(LON_PARQUE)    
w=min(LON_PARQUE) 

incr<- 0.1


if(n > 0){n<- n + incr}else{n<- n + incr}
if(s > 0){s<- s - incr}else{s<- s- incr}
if(e > 0){e<- e + incr}else{e<- e + incr}
if(w > 0){w<- w - incr}else{w<- w- incr}



ul <- round(c(n,w),digits = 2)  #Upper Left
lr <- round(c(s,e), digits = 2)  #Lower Right


lon_location<- seq(lr[1],ul[1],length.out = 100 ) 
lat_location<- seq(ul[2],lr[2], length.out = 100)
data_loc<- expand.grid(lat_location,lon_location)
colnames(data_loc)<- c("x", "y")

spdf <- SpatialPointsDataFrame(coords = data_loc, data = data_loc,
                               proj4string = CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))

if(!dir.exists(here::here('Mapas/Raster_TATANKA/'))){dir.create(here::here('Mapas/Raster_TATANKA/'), recursive = T)}

if(file.exists(here::here('Mapas/Raster_TATANKA/map_raster2.RDS'))){
  map_raster1<- readRDS(here::here('Mapas/Raster_TATANKA/map_raster2.RDS'))
}else{
  map_raster1<- get_elev_raster(spdf, z=12)
  saveRDS(map_raster1,here::here('Mapas/Raster_TATANKA/map_raster2.RDS'))
}

levelplot(map_raster1, par.settings= viridisTheme()) + 
  layer(panel.points(COORD_SIM_D01$LON ,
                     COORD_SIM_D01$LAT, pch=21, cex=2, colour='white', fill= 'white'))+
layer(panel.points(COORD_SIM_D02$LON ,
                   COORD_SIM_D02$LAT, pch=21, cex=1.5, colour='white', fill= 'green'))+
  layer(panel.points(COORD_SIM_D03$LON ,
                     COORD_SIM_D03$LAT, pch=21, cex=1, colour='white', fill= 'orange'))+
  layer(panel.points(LON_PARQUE ,
                     LAT_PARQUE, pch=21, cex=1, colour='white', fill= 'red'))


```

```{r eval= FALSE}
PATH_TO_CSVS<- '/media/oscar/14002CD4002CBF1C/tamaulipas/'

CSV_FILES<- list.files(PATH_TO_CSVS, recursive = T, full.names = T) %>%
  .[str_detect(., '.csv')] %>% 
  .[str_detect(., '2019')]


DOMINIOS<- c('D01', 'D02', 'D03')
LISTA_CORR_LEVEL<- list()
LISTA_DATOS_LEVELS<- list()
for(LEVELS in 1:10){
  LISTA_DATOS<- list()
  LISTA_CORR_DOM<- list()
  for(DOM in 1:3){
    
    CSV_FILES_D01<- CSV_FILES %>% .[str_detect(.,DOMINIOS[DOM])]
    
    
    #CREAMOS LA LISTA COMPLETA
    LISTA_SIM<- list()
    for( i in 1:length(CSV_FILES_D01)){
      TABLA_DOM<- CSV_FILES_D01[i] %>% read.csv(header = T)
      TABLA_DOM$SIM_TIME<- as.numeric(with(TABLA_DOM, difftime(ymd_hms(DATE),ymd_hms(DATE)[1],units="hours") ))

      LISTA_SIM[[i]]<-TABLA_DOM
    }
    
    TABLA_SIM<- bind_rows(LISTA_SIM)
    TABLA_SIM_0<- TABLA_SIM %>% group_split(LEVEL) %>% .[[LEVELS]]
    
    ADD_DISTANCIA<- FALSE
    if(ADD_DISTANCIA){
      
      for(i in 1:nrow(TABLA_SIM_0)){
        TABLA_SIM_0[i, 'DIST']<- distm(TABLA_SIM_0[i, c("LON", "LAT")], c(LON_TNK, LAT_TNK))
      }
      DISTANCIAS_MENORES<- TABLA_SIM_0$DIST %>% unique() %>% .[order(., decreasing = FALSE)] %>% .[1:50]
      
      
      TABLA_SIM_10<- TABLA_SIM_0[TABLA_SIM_0$DIST%in%DISTANCIAS_MENORES, ]
    }else{
      TABLA_SIM_10<- TABLA_SIM_0
    }

    
    
    TABLA_CORR<- data.frame(matrix(ncol = 8))
    for(i in 1:length( TABLA_SIM_10 %>% group_split(LON,LAT))){
      
      TABLA_INDV<- TABLA_SIM_10 %>% group_split(LON,LAT)%>% .[[i]]
      TABLA_INDV$DATE<-ymd_hms(TABLA_INDV$DATE)
      TABLA_1<- TABLA_INDV[TABLA_INDV$SIM_TIME<24,] %>% .[!duplicated(.$DATE),] %>% .[complete.cases(.),]
      TABLA_2<- TABLA_INDV[TABLA_INDV$SIM_TIME>24,] %>% .[!duplicated(.$DATE),] %>% .[complete.cases(.),]
      
      
      INFO_PARQUES<- readRDS(here::here('Data/Parques/PRUEBA_EOLICOS/Historico_PE.RDS'))
      INFO_TATANKA<- INFO_PARQUES[str_detect(INFO_PARQUES$PARQUE, 'Tamaulipas'),]
      TABLA_1_JOIN<- left_join(TABLA_1, INFO_TATANKA , by= 'DATE') %>% .[complete.cases(.),]
      TABLA_2_JOIN<- left_join(TABLA_2, INFO_TATANKA , by= 'DATE') %>% .[complete.cases(.),]
      
      
      
      
      
      TABLA_2_JOIN$PRUDUCCION_DISP_NORM<- (TABLA_2_JOIN$PRUDUCCION_MWH*TABLA_2_JOIN$DISPONIBILIDAD/100 - mean(TABLA_2_JOIN$PRUDUCCION_MWH*TABLA_2_JOIN$DISPONIBILIDAD/100))/sd(TABLA_2_JOIN$PRUDUCCION_MWH*TABLA_2_JOIN$DISPONIBILIDAD/100)
      TABLA_2_JOIN$PRUDUCCION_MWH_NORM<- (TABLA_2_JOIN$PRUDUCCION_MWH - mean(TABLA_2_JOIN$PRUDUCCION_MWH))/sd(TABLA_2_JOIN$PRUDUCCION_MWH)
      
      TABLA_2_JOIN$WS_NORM<- (TABLA_2_JOIN$WS - mean(TABLA_2_JOIN$WS))/sd(TABLA_2_JOIN$WS)
      TABLA_2_JOIN$WS3_NORM<- (TABLA_2_JOIN$WS^3 - mean(TABLA_2_JOIN$WS^3))/sd(TABLA_2_JOIN$WS^3)
      
      
      TABLA_1_JOIN$PRUDUCCION_DISP_NORM<- (TABLA_1_JOIN$PRUDUCCION_MWH*TABLA_1_JOIN$DISPONIBILIDAD/100 - mean(TABLA_1_JOIN$PRUDUCCION_MWH*TABLA_1_JOIN$DISPONIBILIDAD/100))/sd(TABLA_1_JOIN$PRUDUCCION_MWH*TABLA_1_JOIN$DISPONIBILIDAD/100)
      TABLA_1_JOIN$PRUDUCCION_MWH_NORM<- (TABLA_1_JOIN$PRUDUCCION_MWH - mean(TABLA_1_JOIN$PRUDUCCION_MWH))/sd(TABLA_1_JOIN$PRUDUCCION_MWH)
      
      TABLA_1_JOIN$WS_NORM<- (TABLA_1_JOIN$WS - mean(TABLA_1_JOIN$WS))/sd(TABLA_1_JOIN$WS)
      TABLA_1_JOIN$WS3_NORM<- (TABLA_1_JOIN$WS^3 - mean(TABLA_1_JOIN$WS^3))/sd(TABLA_1_JOIN$WS^3)
      
      
      
      
      CORR_WS_1<- cor(TABLA_1_JOIN$WS_NORM, TABLA_1_JOIN$PRUDUCCION_DISP_NORM, use = 'complete.obs')
      CORR_WS3_1<- cor(TABLA_1_JOIN$WS3_NORM, TABLA_1_JOIN$PRUDUCCION_DISP_NORM)
      
      CORR_WS_2<- cor(TABLA_2_JOIN$WS_NORM, TABLA_2_JOIN$PRUDUCCION_DISP_NORM)
      CORR_WS3_2<- cor(TABLA_2_JOIN$WS3_NORM, TABLA_2_JOIN$PRUDUCCION_DISP_NORM)
      
      CORR_WS_WO_NORM_1<- cor(TABLA_1_JOIN$WS, TABLA_1_JOIN$PRUDUCCION_MWH)
      CORR_WS_WO_NORM_2<- cor(TABLA_2_JOIN$WS, TABLA_2_JOIN$PRUDUCCION_MWH)
      
      CORR_WS3_WO_NORM_1<- cor(TABLA_1_JOIN$WS^3, TABLA_1_JOIN$PRUDUCCION_MWH)
      CORR_WS3_WO_NORM_2<- cor(TABLA_2_JOIN$WS^3, TABLA_2_JOIN$PRUDUCCION_MWH)
      
      TABLA_CORR[i,]<- c(CORR_WS_1, CORR_WS3_1, CORR_WS_WO_NORM_1,CORR_WS3_WO_NORM_1, 
                         CORR_WS_2, CORR_WS3_2, CORR_WS_WO_NORM_2,CORR_WS3_WO_NORM_2)
      
      
    }
    
    print(ggplot()+
            geom_line(data = TABLA_1_JOIN, aes(x= DATE, y= PRUDUCCION_MWH_NORM))+
            geom_line(data = TABLA_1_JOIN, aes(x= DATE, y= WS_NORM), col='red')+
            geom_line(data = TABLA_1_JOIN, aes(x= DATE, y= WS3_NORM), col='orange')+
            theme_light())
    
    LISTA_CORR_DOM[[DOM]]<- TABLA_CORR
    LISTA_DATOS[[DOM]]<- TABLA_SIM_0
    
  }
  
  LISTA_CORR_LEVEL[[LEVELS]]<- LISTA_CORR_DOM
  LISTA_DATOS_LEVELS[[LEVELS]]<- LISTA_DATOS
  
}

LISTA_DATOS_NAMED<- LISTA_DATOS_LEVELS %>% lapply(function(x){
  names(x)<- c('D01', 'D02','D03')
  return(x)
})

names(LISTA_DATOS_NAMED)<- paste0('L', seq(1,10,1))



dir.create(here::here('Data/Parques/PRUEBA_EOLICOS/TAMAULIPAS_DATA/'))
saveRDS(LISTA_DATOS_NAMED,here::here('Data/Parques/PRUEBA_EOLICOS/TAMAULIPAS_DATA/LISTA_DATOS.RDS'))
saveRDS(LISTA_CORR_LEVEL,here::here('Data/Parques/PRUEBA_EOLICOS/TAMAULIPAS_DATA/LISTA_CORRELATION.RDS'))


```

```{r}
LISTA_CORR_LEVEL<- readRDS(here::here('Data/Parques/PRUEBA_EOLICOS/TAMAULIPAS_DATA/LISTA_CORRELATION.RDS'))

LISTA_2<- LISTA_CORR_LEVEL %>% lapply(function(x){
  TABLA<- x %>% sapply(function(y){
    colMeans(y)
  })
  colnames(TABLA)<- c('D01', 'D02', 'D03')
  rownames(TABLA)<- c('WS_NORMALIZADO', 'WS3_NORMALIZADO', 'WS_SIN_NORMALIZAR', 'WS3_SIN_NORMALIZAR',
                      '2WS_NORMALIZADO', '2WS3_NORMALIZADO', '2WS_SIN_NORMALIZAR', '2WS3_SIN_NORMALIZAR')
  return(TABLA)
  })

names(LISTA_2)<- paste0('L', seq(1,10,1))

for(x in 1:length(LISTA_2)){
  TABLA<- as.data.frame(unname(LISTA_2[[x]]))
  colnames(TABLA)<- c('D01','D02', 'D03')
  TABLA$LEVEL<- names(LISTA_2)[x]
  TABLA$METHOD<- rownames(LISTA_2[[x]])
  LISTA_2[[x]]<- TABLA
}
TABLA_CORR<- bind_rows(LISTA_2)

TABLA_CORR_WS<- TABLA_CORR[!str_detect(TABLA_CORR$METHOD, 'WS3'),]

TABLA_CORR_WS_MELT_MEAN<- melt(TABLA_CORR_WS, id.vars=c("METHOD", 'LEVEL'))

ggplot(TABLA_CORR_WS_MELT_MEAN) +
  geom_point(aes(x=LEVEL ,y= value, color= METHOD, pch = variable), cex=5)+
  scale_x_discrete(limits=paste0('L', seq(1,10,1)))+
  ggtitle('RESULTADOS DE CORRELACION MEDIA DE LOS 50 PUNTOS MAS CERCANOS DEL DOMINIO')+
  theme_light()





LISTA_MAX<- LISTA_CORR_LEVEL %>% lapply(function(x){
  TABLA<- x %>% sapply(function(y){
    apply(y,2,max)
  })
  colnames(TABLA)<- c('D01', 'D02', 'D03')
  rownames(TABLA)<- c('WS_NORMALIZADO', 'WS3_NORMALIZADO', 'WS_SIN_NORMALIZAR', 'WS3_SIN_NORMALIZAR',
                      '2WS_NORMALIZADO', '2WS3_NORMALIZADO', '2WS_SIN_NORMALIZAR', '2WS3_SIN_NORMALIZAR')
  return(TABLA)
})
names(LISTA_MAX)<- paste0('L', seq(1,10,1))
for(x in 1:length(LISTA_MAX)){
  TABLA<- as.data.frame(unname(LISTA_MAX[[x]]))
  colnames(TABLA)<- c('D01','D02', 'D03')
  TABLA$LEVEL<- names(LISTA_MAX)[x]
  TABLA$METHOD<- rownames(LISTA_MAX[[x]])
  LISTA_MAX[[x]]<- TABLA
}
TABLA_CORR<- bind_rows(LISTA_MAX) 

TABLA_CORR_WS<- TABLA_CORR[!str_detect(TABLA_CORR$METHOD, 'WS3'),]

TABLA_CORR_WS_MELT_MAX<- melt(TABLA_CORR_WS, id.vars=c("METHOD", 'LEVEL'))


ggplot(TABLA_CORR_WS_MELT_MAX) +
  geom_point(aes(x=LEVEL ,y= value, color= METHOD, pch = variable), cex=5)+
  scale_x_discrete(limits=paste0('L', seq(1,10,1)))+
  ggtitle('RESULTADOS DE CORRELACION MAXIMA DE LOS 50 PUNTOS MAS CERCANOS DEL DOMINIO')+
  theme_light()



```


```{r}
TABLA_CORR_WS_MELT_MAX %>%  filter(variable=='D01') %>% .[which.max(.$value),]
TABLA_CORR_WS_MELT_MAX %>%  filter(variable=='D02') %>% .[which.max(.$value),]
TABLA_CORR_WS_MELT_MAX %>%  filter(variable=='D03') %>% .[which.max(.$value),]

```

```{r}
LISTA_DATOS_LEVELS<- readRDS(here::here('Data/Parques/PRUEBA_EOLICOS/TAMAULIPAS_DATA/LISTA_DATOS.RDS'))




TABLA_CORR<- data.frame(matrix(ncol = 6))
for(i in 1:length(LISTA_DATOS_LEVELS$L2$D01 %>% group_split(LON,LAT))){
  TABLA_D01_L2<- LISTA_DATOS_LEVELS$L2$D01 %>% group_split(LON,LAT)%>% .[[i]]
  TABLA_D01_L2$DATE<-ymd_hms(TABLA_D01_L2$DATE)
  TABLA_1<- TABLA_D01_L2[TABLA_D01_L2$SIM_TIME<24,] %>% .[!duplicated(.$DATE),] %>% .[complete.cases(.),]
  TABLA_2<- TABLA_D01_L2[TABLA_D01_L2$SIM_TIME>24,] %>% .[!duplicated(.$DATE),] %>% .[complete.cases(.),]


  INFO_PARQUES<- readRDS(here::here('Data/Parques/PRUEBA_EOLICOS/Historico_PE.RDS'))
  INFO_TATANKA<- INFO_PARQUES[str_detect(INFO_PARQUES$PARQUE, 'Tamaulipas'),]
  TABLA_1_JOIN<- left_join(TABLA_1, INFO_TATANKA , by= 'DATE') %>% .[complete.cases(.),]
  TABLA_2_JOIN<- left_join(TABLA_2, INFO_TATANKA , by= 'DATE') %>% .[complete.cases(.),]


  TABLA_1_JOIN$PRUDUCCION_DISP_NORM<- (TABLA_1_JOIN$PRUDUCCION_MWH*TABLA_1_JOIN$DISPONIBILIDAD/100-mean(TABLA_1_JOIN$PRUDUCCION_MWH*TABLA_1_JOIN$DISPONIBILIDAD/100))/sd(TABLA_1_JOIN$PRUDUCCION_MWH*TABLA_1_JOIN$DISPONIBILIDAD/100)
  
  TABLA_1_JOIN$PRUDUCCION_MWH_NORM<- (TABLA_1_JOIN$PRUDUCCION_MWH - mean(TABLA_1_JOIN$PRUDUCCION_MWH))/sd(TABLA_1_JOIN$PRUDUCCION_MWH)

  TABLA_1_JOIN$WS_NORM<- (TABLA_1_JOIN$WS - mean(TABLA_1_JOIN$WS))/sd(TABLA_1_JOIN$WS)





  CORR_WS_DISP_NORM<- cor(TABLA_1_JOIN$WS_NORM, TABLA_1_JOIN$PRUDUCCION_DISP_NORM, use = 'complete.obs')
  CORR_WS_NO_DISP_NORM<- cor(TABLA_1_JOIN$WS_NORM, TABLA_1_JOIN$PRUDUCCION_MWH_NORM, use = 'complete.obs')

  CORR_WS_NO_NORM_NO_DISP<- cor(TABLA_1_JOIN$WS, TABLA_1_JOIN$PRUDUCCION_MWH)
  CORR_WS_NO_NORM_DISP<- cor(TABLA_1_JOIN$WS, TABLA_1_JOIN$PRUDUCCION_MWH*TABLA_1_JOIN$DISPONIBILIDAD/100)


  TABLA_CORR[i,]<- c(CORR_WS_DISP_NORM, CORR_WS_NO_DISP_NORM, 
                     CORR_WS_NO_NORM_NO_DISP, CORR_WS_NO_NORM_DISP, 
                     TABLA_D01_L2$LON %>% unique(),
                     TABLA_D01_L2$LAT %>% unique())
  
}

colnames(TABLA_CORR)<- c('WS_NORM_PRO_NORM_DISP', 'WS_NORM_PRO_NORM', 
                         'WS_PRO', 'WS_PRO_DISP', 'LON','LAT')


TABLA_CORR[which(TABLA_CORR==max(TABLA_CORR[,1:4]), arr.ind = TRUE)[1],]

LON_MAX<-TABLA_CORR[which(TABLA_CORR==max(TABLA_CORR[,1:4]), arr.ind = TRUE)[1],c("LON")]
LAT_MAX<-TABLA_CORR[which(TABLA_CORR==max(TABLA_CORR[,1:4]), arr.ind = TRUE)[1],c("LAT")]

TABLA_MAX <- LISTA_DATOS_LEVELS$L2$D01 %>% filter(LON==LON_MAX, LAT==LAT_MAX)
TABLA_MAX$DATE<-ymd_hms(TABLA_MAX$DATE)
TABLA_MAX1<- TABLA_MAX[TABLA_MAX$SIM_TIME<24,] %>% .[!duplicated(.$DATE),] %>% .[complete.cases(.),]


INFO_PARQUES<- readRDS(here::here('Data/Parques/PRUEBA_EOLICOS/Historico_PE.RDS'))
INFO_TATANKA<- INFO_PARQUES[str_detect(INFO_PARQUES$PARQUE, 'Tamaulipas'),]




TABLA_MAX_JOIN<- left_join(TABLA_MAX1, INFO_TATANKA , by= 'DATE') %>% .[complete.cases(.),]

TABLA_MAX_JOIN$PRUDUCCION_MWH_NORM<- (TABLA_MAX_JOIN$PRUDUCCION_MWH - mean(TABLA_MAX_JOIN$PRUDUCCION_MWH))/sd(TABLA_MAX_JOIN$PRUDUCCION_MWH)

TABLA_MAX_JOIN$WS_NORM<- (TABLA_MAX_JOIN$WS - mean(TABLA_MAX_JOIN$WS))/sd(TABLA_MAX_JOIN$WS)

TABLA_MAX_D01<- TABLA_MAX_JOIN

 
```

UNA COSA CURIOSA DE ANALIZAR ES QUE LA CORRELACION DE LA VARIABLE NORMALIZADA Y SIN NORMALIZAR ES IGUAL... Y QUE TENIENDO EN CUENTA LA DISPONIBILIDAD NO SE CONSIGUE NADA.
 

 
 

```{r eval=FALSE}
TABLA_MAX_JOIN %>% 
  ggplot() + 
  geom_line(aes(y= SMA(WS_NORM, 12), x= DATE), col = 'blue')+
  geom_line(aes(y= PRUDUCCION_MWH_NORM, x= DATE), col = 'red')+
  theme_light()
```


```{r}
LISTA_DATOS_LEVELS<- readRDS(here::here('Data/Parques/PRUEBA_EOLICOS/TAMAULIPAS_DATA/LISTA_DATOS.RDS'))




TABLA_CORR<- data.frame(matrix(ncol = 6))
for(i in 1:length(LISTA_DATOS_LEVELS$L3$D02 %>% group_split(LON,LAT))){
  TABLA_D02_L3<- LISTA_DATOS_LEVELS$L3$D02 %>% group_split(LON,LAT)%>% .[[i]]
  TABLA_D02_L3$DATE<-ymd_hms(TABLA_D02_L3$DATE)
  TABLA_1<- TABLA_D02_L3[TABLA_D02_L3$SIM_TIME<24,] %>% .[!duplicated(.$DATE),] %>% .[complete.cases(.),]
  TABLA_2<- TABLA_D02_L3[TABLA_D02_L3$SIM_TIME>24,] %>% .[!duplicated(.$DATE),] %>% .[complete.cases(.),]


  INFO_PARQUES<- readRDS(here::here('Data/Parques/PRUEBA_EOLICOS/Historico_PE.RDS'))
  INFO_TATANKA<- INFO_PARQUES[str_detect(INFO_PARQUES$PARQUE, 'Tamaulipas'),]
  TABLA_1_JOIN<- left_join(TABLA_1, INFO_TATANKA , by= 'DATE') %>% .[complete.cases(.),]
  TABLA_2_JOIN<- left_join(TABLA_2, INFO_TATANKA , by= 'DATE') %>% .[complete.cases(.),]


  TABLA_1_JOIN$PRUDUCCION_DISP_NORM<- (TABLA_1_JOIN$PRUDUCCION_MWH*TABLA_1_JOIN$DISPONIBILIDAD/100-mean(TABLA_1_JOIN$PRUDUCCION_MWH*TABLA_1_JOIN$DISPONIBILIDAD/100))/sd(TABLA_1_JOIN$PRUDUCCION_MWH*TABLA_1_JOIN$DISPONIBILIDAD/100)
  
  TABLA_1_JOIN$PRUDUCCION_MWH_NORM<- (TABLA_1_JOIN$PRUDUCCION_MWH - mean(TABLA_1_JOIN$PRUDUCCION_MWH))/sd(TABLA_1_JOIN$PRUDUCCION_MWH)

  TABLA_1_JOIN$WS_NORM<- (TABLA_1_JOIN$WS - mean(TABLA_1_JOIN$WS))/sd(TABLA_1_JOIN$WS)





  CORR_WS_DISP_NORM<- cor(TABLA_1_JOIN$WS_NORM, TABLA_1_JOIN$PRUDUCCION_DISP_NORM, use = 'complete.obs')
  CORR_WS_NO_DISP_NORM<- cor(TABLA_1_JOIN$WS_NORM, TABLA_1_JOIN$PRUDUCCION_MWH_NORM, use = 'complete.obs')

  CORR_WS_NO_NORM_NO_DISP<- cor(TABLA_1_JOIN$WS, TABLA_1_JOIN$PRUDUCCION_MWH)
  CORR_WS_NO_NORM_DISP<- cor(TABLA_1_JOIN$WS, TABLA_1_JOIN$PRUDUCCION_MWH*TABLA_1_JOIN$DISPONIBILIDAD/100)


  TABLA_CORR[i,]<- c(CORR_WS_DISP_NORM, CORR_WS_NO_DISP_NORM, 
                     CORR_WS_NO_NORM_NO_DISP, CORR_WS_NO_NORM_DISP, 
                     TABLA_D02_L3$LON %>% unique(),
                     TABLA_D02_L3$LAT %>% unique())
  
}

colnames(TABLA_CORR)<- c('WS_NORM_PRO_NORM_DISP', 'WS_NORM_PRO_NORM', 
                         'WS_PRO', 'WS_PRO_DISP', 'LON','LAT')


TABLA_CORR[which(TABLA_CORR==max(TABLA_CORR[,1:4]), arr.ind = TRUE)[1],]

LON_MAX<-TABLA_CORR[which(TABLA_CORR==max(TABLA_CORR[,1:4]), arr.ind = TRUE)[1],c("LON")]
LAT_MAX<-TABLA_CORR[which(TABLA_CORR==max(TABLA_CORR[,1:4]), arr.ind = TRUE)[1],c("LAT")]

TABLA_MAX <- LISTA_DATOS_LEVELS$L3$D02 %>% filter(LON==LON_MAX, LAT==LAT_MAX)
TABLA_MAX$DATE<-ymd_hms(TABLA_MAX$DATE)
TABLA_MAX1<- TABLA_MAX[TABLA_MAX$SIM_TIME<24,] %>% .[!duplicated(.$DATE),] %>% .[complete.cases(.),]


INFO_PARQUES<- readRDS(here::here('Data/Parques/PRUEBA_EOLICOS/Historico_PE.RDS'))
INFO_TATANKA<- INFO_PARQUES[str_detect(INFO_PARQUES$PARQUE, 'Tamaulipas'),]




TABLA_MAX_JOIN<- left_join(TABLA_MAX1, INFO_TATANKA , by= 'DATE') %>% .[complete.cases(.),]

TABLA_MAX_JOIN$PRUDUCCION_MWH_NORM<- (TABLA_MAX_JOIN$PRUDUCCION_MWH - mean(TABLA_MAX_JOIN$PRUDUCCION_MWH))/sd(TABLA_MAX_JOIN$PRUDUCCION_MWH)

TABLA_MAX_JOIN$WS_NORM<- (TABLA_MAX_JOIN$WS - mean(TABLA_MAX_JOIN$WS))/sd(TABLA_MAX_JOIN$WS)
TABLA_MAX_D02<- TABLA_MAX_JOIN


```
```{r}
LISTA_DATOS_LEVELS<- readRDS(here::here('Data/Parques/PRUEBA_EOLICOS/TAMAULIPAS_DATA/LISTA_DATOS.RDS'))




TABLA_CORR<- data.frame(matrix(ncol = 6))
for(i in 1:length(LISTA_DATOS_LEVELS$L3$D03 %>% group_split(LON,LAT))){
  TABLA_D03_L3<- LISTA_DATOS_LEVELS$L3$D03 %>% group_split(LON,LAT)%>% .[[i]]
  TABLA_D03_L3$DATE<-ymd_hms(TABLA_D03_L3$DATE)
  TABLA_1<- TABLA_D03_L3[TABLA_D03_L3$SIM_TIME<24,] %>% .[!duplicated(.$DATE),] %>% .[complete.cases(.),]
  TABLA_2<- TABLA_D03_L3[TABLA_D03_L3$SIM_TIME>24,] %>% .[!duplicated(.$DATE),] %>% .[complete.cases(.),]


  INFO_PARQUES<- readRDS(here::here('Data/Parques/PRUEBA_EOLICOS/Historico_PE.RDS'))
  INFO_TATANKA<- INFO_PARQUES[str_detect(INFO_PARQUES$PARQUE, 'Tamaulipas'),]
  TABLA_1_JOIN<- left_join(TABLA_1, INFO_TATANKA , by= 'DATE') %>% .[complete.cases(.),]
  TABLA_2_JOIN<- left_join(TABLA_2, INFO_TATANKA , by= 'DATE') %>% .[complete.cases(.),]


  TABLA_1_JOIN$PRUDUCCION_DISP_NORM<- (TABLA_1_JOIN$PRUDUCCION_MWH*TABLA_1_JOIN$DISPONIBILIDAD/100-mean(TABLA_1_JOIN$PRUDUCCION_MWH*TABLA_1_JOIN$DISPONIBILIDAD/100))/sd(TABLA_1_JOIN$PRUDUCCION_MWH*TABLA_1_JOIN$DISPONIBILIDAD/100)
  
  TABLA_1_JOIN$PRUDUCCION_MWH_NORM<- (TABLA_1_JOIN$PRUDUCCION_MWH - mean(TABLA_1_JOIN$PRUDUCCION_MWH))/sd(TABLA_1_JOIN$PRUDUCCION_MWH)

  TABLA_1_JOIN$WS_NORM<- (TABLA_1_JOIN$WS - mean(TABLA_1_JOIN$WS))/sd(TABLA_1_JOIN$WS)





  CORR_WS_DISP_NORM<- cor(TABLA_1_JOIN$WS_NORM, TABLA_1_JOIN$PRUDUCCION_DISP_NORM, use = 'complete.obs')
  CORR_WS_NO_DISP_NORM<- cor(TABLA_1_JOIN$WS_NORM, TABLA_1_JOIN$PRUDUCCION_MWH_NORM, use = 'complete.obs')

  CORR_WS_NO_NORM_NO_DISP<- cor(TABLA_1_JOIN$WS, TABLA_1_JOIN$PRUDUCCION_MWH)
  CORR_WS_NO_NORM_DISP<- cor(TABLA_1_JOIN$WS, TABLA_1_JOIN$PRUDUCCION_MWH*TABLA_1_JOIN$DISPONIBILIDAD/100)


  TABLA_CORR[i,]<- c(CORR_WS_DISP_NORM, CORR_WS_NO_DISP_NORM, 
                     CORR_WS_NO_NORM_NO_DISP, CORR_WS_NO_NORM_DISP, 
                     TABLA_D03_L3$LON %>% unique(),
                     TABLA_D03_L3$LAT %>% unique())
  
}

colnames(TABLA_CORR)<- c('WS_NORM_PRO_NORM_DISP', 'WS_NORM_PRO_NORM', 
                         'WS_PRO', 'WS_PRO_DISP', 'LON','LAT')


TABLA_CORR[which(TABLA_CORR==max(TABLA_CORR[,1:4]), arr.ind = TRUE)[1],]

LON_MAX<-TABLA_CORR[which(TABLA_CORR==max(TABLA_CORR[,1:4]), arr.ind = TRUE)[1],c("LON")]
LAT_MAX<-TABLA_CORR[which(TABLA_CORR==max(TABLA_CORR[,1:4]), arr.ind = TRUE)[1],c("LAT")]

TABLA_MAX <- LISTA_DATOS_LEVELS$L3$D03 %>% filter(LON==LON_MAX, LAT==LAT_MAX)
TABLA_MAX$DATE<-ymd_hms(TABLA_MAX$DATE)
TABLA_MAX1<- TABLA_MAX[TABLA_MAX$SIM_TIME<24,] %>% .[!duplicated(.$DATE),] %>% .[complete.cases(.),]


INFO_PARQUES<- readRDS(here::here('Data/Parques/PRUEBA_EOLICOS/Historico_PE.RDS'))
INFO_TATANKA<- INFO_PARQUES[str_detect(INFO_PARQUES$PARQUE, 'Tamaulipas'),]




TABLA_MAX_JOIN<- left_join(TABLA_MAX1, INFO_TATANKA , by= 'DATE') %>% .[complete.cases(.),]

TABLA_MAX_JOIN$PRUDUCCION_MWH_NORM<- (TABLA_MAX_JOIN$PRUDUCCION_MWH - mean(TABLA_MAX_JOIN$PRUDUCCION_MWH))/sd(TABLA_MAX_JOIN$PRUDUCCION_MWH)

TABLA_MAX_JOIN$WS_NORM<- (TABLA_MAX_JOIN$WS - mean(TABLA_MAX_JOIN$WS))/sd(TABLA_MAX_JOIN$WS)
TABLA_MAX_D03<- TABLA_MAX_JOIN



```

 
```{r}
  ggplot() + 
  geom_line(data = TABLA_MAX_D01 , aes(y= WS, x= DATE), col = 'blue')+
  geom_line(data = TABLA_MAX_D02 , aes(y= WS, x= DATE), col = 'red')+
  geom_line(data = TABLA_MAX_D03 , aes(y= WS, x= DATE), col = 'black')+
  ylab('')+
  theme_light()

```
```{r}
library(openair)

windRose(TABLA_MAX_D01, ws= 'WS', wd = 'WD',paddle = FALSE)
windRose(TABLA_MAX_D02, ws= 'WS', wd = 'WD',paddle = FALSE)
windRose(TABLA_MAX_D03, ws= 'WS', wd = 'WD',paddle = FALSE)


```

```{r}
NAM12_DATA<- readRDS(here::here('Data/Parques/PRUEBA_EOLICOS/TAMAULIPAS_DATA/NAM_12_TAMAULIPAS.RDS'))

LISTA_DATOS_LEVELS<- readRDS(here::here('Data/Parques/PRUEBA_EOLICOS/TAMAULIPAS_DATA/LISTA_DATOS.RDS'))




TABLA_CORR<- data.frame(matrix(ncol = 10))
k<- 1 

for(point in  NAM12_DATA %>% group_by(LON, LAT) %>% group_split() ){
  
  TABLA_NAM<-point
INFO_PARQUES<- readRDS(here::here('Data/Parques/PRUEBA_EOLICOS/Historico_PE.RDS'))
INFO_TATANKA<- INFO_PARQUES[str_detect(INFO_PARQUES$PARQUE, 'Tamaulipas'),]


TABLA_1_JOIN<- left_join(TABLA_NAM, INFO_TATANKA , by= 'DATE') %>% .[complete.cases(.),]


TABLA_1_JOIN$PRUDUCCION_DISP_NORM<- (TABLA_1_JOIN$PRUDUCCION_MWH*TABLA_1_JOIN$DISPONIBILIDAD/100-mean(TABLA_1_JOIN$PRUDUCCION_MWH*TABLA_1_JOIN$DISPONIBILIDAD/100))/sd(TABLA_1_JOIN$PRUDUCCION_MWH*TABLA_1_JOIN$DISPONIBILIDAD/100)

TABLA_1_JOIN$PRUDUCCION_MWH_NORM<- (TABLA_1_JOIN$PRUDUCCION_MWH - mean(TABLA_1_JOIN$PRUDUCCION_MWH))/sd(TABLA_1_JOIN$PRUDUCCION_MWH)

TABLA_1_JOIN$WS_NORM10<- (TABLA_1_JOIN$WS10 - mean(TABLA_1_JOIN$WS10))/sd(TABLA_1_JOIN$WS10)
TABLA_1_JOIN$WS_NORM80<- (TABLA_1_JOIN$WS80 - mean(TABLA_1_JOIN$WS80))/sd(TABLA_1_JOIN$WS80)





CORR_WS_DISP_NORM10<- cor(TABLA_1_JOIN$WS_NORM10, TABLA_1_JOIN$PRUDUCCION_DISP_NORM, use = 'complete.obs')
CORR_WS_DISP_NORM80<- cor(TABLA_1_JOIN$WS_NORM80, TABLA_1_JOIN$PRUDUCCION_DISP_NORM, use = 'complete.obs')

CORR_WS_NO_DISP_NORM10<- cor(TABLA_1_JOIN$WS_NORM10, TABLA_1_JOIN$PRUDUCCION_MWH_NORM, use = 'complete.obs')
CORR_WS_NO_DISP_NORM80<- cor(TABLA_1_JOIN$WS_NORM80, TABLA_1_JOIN$PRUDUCCION_MWH_NORM, use = 'complete.obs')

CORR_WS_NO_NORM_NO_DISP10<- cor(TABLA_1_JOIN$WS10, TABLA_1_JOIN$PRUDUCCION_MWH)
CORR_WS_NO_NORM_DISP10<- cor(TABLA_1_JOIN$WS10, TABLA_1_JOIN$PRUDUCCION_MWH*TABLA_1_JOIN$DISPONIBILIDAD/100)


CORR_WS_NO_NORM_NO_DISP80<- cor(TABLA_1_JOIN$WS80, TABLA_1_JOIN$PRUDUCCION_MWH)
CORR_WS_NO_NORM_DISP80<- cor(TABLA_1_JOIN$WS80, TABLA_1_JOIN$PRUDUCCION_MWH*TABLA_1_JOIN$DISPONIBILIDAD/100)


TABLA_CORR[k,]<- c(CORR_WS_DISP_NORM10,
                   CORR_WS_DISP_NORM80,
                   CORR_WS_NO_DISP_NORM10,
                   CORR_WS_NO_DISP_NORM80,
                   CORR_WS_NO_NORM_NO_DISP10,
                   CORR_WS_NO_NORM_NO_DISP80, 
                   CORR_WS_NO_NORM_DISP10,
                   CORR_WS_NO_NORM_DISP80,
                   TABLA_1_JOIN$LON.x %>% unique(),
                   TABLA_1_JOIN$LAT.x %>% unique())

k<- k+1
}

colnames(TABLA_CORR)<- c('WS_NORM_PRO_NORM_DISP10','WS_NORM_PRO_NORM_DISP80',
                          'WS_NORM_PRO_NORM10','WS_NORM_PRO_NORM80', 
                         'WS_PRO10','WS_PRO80',
                         'WS_PRO_DISP10', 'WS_PRO_DISP80', 'LON','LAT')




TABLA_CORR[which(TABLA_CORR==max(TABLA_CORR[,1:8]), arr.ind = TRUE)[1],1:10]

LON_MAX<-TABLA_CORR[which(TABLA_CORR==max(TABLA_CORR[,1:8]), arr.ind = TRUE)[1],c("LON")]
LAT_MAX<-TABLA_CORR[which(TABLA_CORR==max(TABLA_CORR[,1:8]), arr.ind = TRUE)[1],c("LAT")]

TABLA_MAX_NAM <- NAM12_DATA%>% filter(LON==LON_MAX, LAT==LAT_MAX)



INFO_PARQUES<- readRDS(here::here('Data/Parques/PRUEBA_EOLICOS/Historico_PE.RDS'))
INFO_TATANKA<- INFO_PARQUES[str_detect(INFO_PARQUES$PARQUE, 'Tamaulipas'),]




TABLA_MAX_JOIN_NAM<- left_join(TABLA_MAX_NAM, INFO_TATANKA , by= 'DATE') %>% .[complete.cases(.),]





TABLA_MAX_JOIN_NAM$PRUDUCCION_MWH_NORM<- (TABLA_MAX_JOIN_NAM$PRUDUCCION_MWH - mean(TABLA_MAX_JOIN_NAM$PRUDUCCION_MWH))/sd(TABLA_MAX_JOIN_NAM$PRUDUCCION_MWH)

TABLA_MAX_JOIN_NAM$WS_NORM<- (TABLA_MAX_JOIN_NAM$WS80 - mean(TABLA_MAX_JOIN_NAM$WS80))/sd(TABLA_MAX_JOIN_NAM$WS80)





tablad01<- TABLA_MAX_D01[,c('DATE', "WS", "WD", "WS_NORM", "PRUDUCCION_MWH","PRUDUCCION_MWH_NORM")]
colnames(tablad01)<- c('DATE', colnames(tablad01)[2:length(tablad01)] %>% paste0('D01'))

tablad02<- TABLA_MAX_D02[,c('DATE', "WS", "WD", "WS_NORM", "PRUDUCCION_MWH","PRUDUCCION_MWH_NORM")]
colnames(tablad02)<- c('DATE', colnames(tablad02)[2:length(tablad02)] %>% paste0('D02'))

tablad03<- TABLA_MAX_D03[,c('DATE', "WS", "WD", "WS_NORM", "PRUDUCCION_MWH","PRUDUCCION_MWH_NORM")]
colnames(tablad03)<-  c('DATE', colnames(tablad03)[2:length(tablad03)] %>% paste0('D03'))


tablanam<-  TABLA_MAX_JOIN_NAM[,c('DATE', "WS10","WS80","WD10", "WD80" ,
                                  "WS_NORM", "PRUDUCCION_MWH","PRUDUCCION_MWH_NORM")]
colnames(tablanam)<-  c('DATE', colnames(tablanam)[2:length(tablanam)] %>% paste0('NAM'))


TABLA_ALL_MODELS<- left_join(tablad01,tablad02,by= 'DATE')
TABLA_ALL_MODELS<- left_join(TABLA_ALL_MODELS,tablad03,  by= 'DATE')
TABLA_ALL_MODELS<- left_join(TABLA_ALL_MODELS, tablanam, by= 'DATE')



TABLA_ALL_MODELS %>% .[!is.na(TABLA_ALL_MODELS$WS_NORMNAM), ]%>%  ggplot()+
  geom_line(aes(x= DATE, y = WS_NORMD01),colour= 'red')+
  geom_line(aes(x= DATE, y = WS_NORMD02),colour= 'orange')+
  geom_line(aes(x= DATE, y = WS_NORMD03), colour= 'green')+
  geom_line(aes(x= DATE, y = WS_NORMNAM), colour= 'blue')+
  geom_line(aes(x= DATE, y = PRUDUCCION_MWH_NORMNAM))+
  ylab('NORMALIZED VARIABLES')+
  xlab('DATE')+
  labs(subtitle = 'VERDE = WRF D03
          NARANJA = WRF D02
          ROJO = WRF D01
          AZUL = NAM12
          NEGRO = PRODUCCION')+
  theme_light()



```

```{r results='show'}
TABLA_ACCURACY<- data.frame(matrix(ncol = 5))
library(forecast)
TABLA_ACCURACY[1,]<- c(accuracy(TABLA_ALL_MODELS$WS_NORMD01, TABLA_ALL_MODELS$PRUDUCCION_MWH_NORMD01))
TABLA_ACCURACY[2,]<- c(accuracy(TABLA_ALL_MODELS$WS_NORMD02, TABLA_ALL_MODELS$PRUDUCCION_MWH_NORMD01))
TABLA_ACCURACY[3,]<- c(accuracy(TABLA_ALL_MODELS$WS_NORMD03, TABLA_ALL_MODELS$PRUDUCCION_MWH_NORMD01))
TABLA_ACCURACY[4,]<- c(accuracy(TABLA_ALL_MODELS$WS_NORMNAM, TABLA_ALL_MODELS$PRUDUCCION_MWH_NORMD01))

colnames(TABLA_ACCURACY)<- c('ME', 'RMSE', 'MAE', 'MPE', 'MAPE')
rownames(TABLA_ACCURACY)<- c('WRF D01','WRF D02','WRF D03','NAM12')

kable(TABLA_ACCURACY)

```



```{r fig.height=6, fig.width=6}
library(plotrix)


taylor.diagram(TABLA_ALL_MODELS$PRUDUCCION_MWH_NORMD01, TABLA_ALL_MODELS$PRUDUCCION_MWH_NORMD01, show.gamma = TRUE)
taylor.diagram(TABLA_ALL_MODELS$WS_NORMD01, TABLA_ALL_MODELS$PRUDUCCION_MWH_NORMD01, add = TRUE, col = 'red')
taylor.diagram(TABLA_ALL_MODELS$WS_NORMD02, TABLA_ALL_MODELS$PRUDUCCION_MWH_NORMD01, add = TRUE, col = 'orange')
taylor.diagram(TABLA_ALL_MODELS$WS_NORMD03, TABLA_ALL_MODELS$PRUDUCCION_MWH_NORMD01, add = TRUE, , col = 'green')
taylor.diagram(TABLA_ALL_MODELS$WS_NORMNAM, TABLA_ALL_MODELS$PRUDUCCION_MWH_NORMD01, add = TRUE, , col = 'blue')

lpos<-1.5*sd(TABLA_ALL_MODELS$PRUDUCCION_MWH_NORMD01)
# add a legend
legend(lpos,lpos-0.2,legend=c('D01', 'D02','D03', 'NAM12'),
       pch=19,col=c('red', 'orange', 'green', 'blue'))
```












